version: "3.9"

services:
  ai-devbot:
    build: .
    container_name: ai-devbot
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./vectorstore:/app/vectorstore
    environment:
      - DATABASE_URL=postgresql://devbot_user:devbot_pass@db:5432/devbot_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: ai-devbot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devbot_user
      POSTGRES_PASSWORD: devbot_pass
      POSTGRES_DB: devbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
